freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script: pkg install -y alsa-lib cmake evdev-proto flac git libao libudev-devd libzip mesa-libs pkgconf png pulseaudio sdl2
  script:
    - cmake -B build -DCMAKE_BUILD_TYPE=Release
    - cmake --build build --config Release --parallel 2
