name: Update GCS Index
on:
  workflow_run:
    workflows:
      - C/C++ CI
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup google cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: Authenticate to google cloud platform
      id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        create_credentials_file: 'true'
        access_token_lifetime: 1200s

    - name: Generate index.json
      run: |
        gcloud storage ls --json -r gs://gdxsv/flycast-builds > list.json
        cat list.json | jq 'def c(str): str | (split(".")[0] + "Z") | fromdate; [.[] | select(.metadata != null)] | sort_by(c(.metadata.timeCreated))' > index.json
        gcloud storage cp index.json gs://gdxsv/flycast-builds/index.json
        
