name: RunGame

on:
  workflow_dispatch:
    inputs:
      flycast-url:
        description: 'Flycast download url'
        default: ''
        required: true
      run-function:
        description: 'First argument of run.py'
        default: 'rbk_test_random'
        required: true
      iteration:
        description: 'Number of iteration'
        default: '3'
        required: true
      timeout:
        description: 'Timeout seconds for single iteration'
        default: '120'
        required: true
      maxrebattle:
        description: 'Max rebattle'
        default: '1'
        required: true

jobs:
  run-game:
    name: RunGame
    runs-on: [win-mini]
    env:
      N: 4
      ROM: "C:\\rom\\gdx-disc2\\gdx-disc2.gdi"
      FLYCAST: ${{ github.event.inputs.flycast-url }}
      ITERATION: ${{ github.event.inputs.iteration }}
      TIMEOUT: ${{ github.event.inputs.timeout }}
      MAXREBATTLE: ${{ github.event.inputs.maxrebattle }}
    steps:
    - uses: actions/checkout@v3
    - run: python run.py ${{ github.event.inputs.run-function }}
